#ifndef VULKAN_ENGINE_VENGINE_COMMON_H
#define VULKAN_ENGINE_VENGINE_COMMON_H

enum class DrawMode
{
    NORMAL,
    DRAWINDEXED,
    DRAWINDIRECT,
    DRAWINDEXEDINDIRECT
};

#endif // !VULKAN_ENGINE_VENGINE_COMMON_H
